### ISSUE TITLE
Update latest version 

### ISSUE THREAD

**Issue by ninhlh2** [dhblooo/Rapfi-gomocup#2]
Would you please commit latest version of this app?
It is a strong engine.

Thanks

**Comment by yllgl** [comment]
> Would you please commit latest version of this app?
> It is a strong engine.
> 
> Thanks

Do you understand the code? I don't understand what some variables means. Could you give me some advice?
```C++
enum Pattern : UInt8 {
	DEAD, 
	B1,   F1,
	B2J0, B2J2, 
	F2J0, F2J1, F2J2,         
	B3J0, B3J1, B3J2,
	F3J0, F3J1,
	B4,   F4,
	F5
};
class Evaluator {
private:
	static Pattern PATTERN[256][256];  // 65536 = 256 * 256 = 4 ^ 8//what is this?
	static PatternCode PCODE[16][16][16][16];  // 65536 = 16 ^ 4//what is this?
        static Pattern4 PATTERN4[3876];//what is this?

protected:
	static short Score[3876];
	static short Value[3876];

	struct Cell {
		UInt8 key[4][2]; //what is this?
		Pattern pattern[2][4];
		short score[2];
		short eval[2];
		Pattern4 pattern4[2];
		UInt8 cand;//what is this?
		bool isLose;
        }
}
```

What does Pattern `B3J2` mean? Does it mean o●●xx●o pattern where x means empty? And `F2J2` means ●xx●?
what does `PCODE[16][16][16][16]` mean? Why is it four dimensions? How does the magic value of 3876  come from?
What key[4][2] in struct Cell mean? And what does `cand` in Cell struct mean?
