### ISSUE TITLE
开局直接下0,0，windows有概率会报错。

### ISSUE THREAD

**Issue by amanohanei** [dhblooo/Rapfi-gomocup#3]
0x00007FF6B7A20A28 处(位于 pbrain-rapfi.exe 中)引发的异常: 0xC0000005: 写入位置 0x0000028E36642906 时发生访问冲突。

目前没搞清楚为什么有时能正常通过有时会异常，我尝试将他移植到Linux平台运行，开局输入turn 0,0必定报错。

**Comment by amanohanei** [comment]
```
void Evaluator::expendCand(Pos pos, int fillDist, int lineDist) {
	board->expendCandArea(pos, MAX(lineDist, fillDist));
	int x = CoordX(pos), y = CoordY(pos);
	Pos p;
	for (int xi = -fillDist; xi <= fillDist; xi++) {
		for (int yi = -fillDist; yi <= fillDist; yi++) {
			if (xi == 0 && yi == 0) continue;
			p = POS(x + xi, y + yi);
			if (board->isEmpty(p) && cell(p).cand == 0) {
				cell(p).cand++;
			}
		}
	}
	p = POS(x, y);
	for (int i = MAX(3, fillDist + 1); i <= lineDist; i++) {
		for (int k = 0; k < 8; k++)
			cell(p + RANGE_NEIGHBOR[k] * i).cand++;
	}
}
```
Evaluator.cpp:728  

cell(p + RANGE_NEIGHBOR[k] * i).cand++ 这里， x=0,y=0的情况p = 132,lineDist = 5， p + RANGE_NEIGHBOR[k] * i <0就报错了
可有概率通过是为什么？cells[-xx]刚好能访问？

**Comment by dhbloo** [comment]
Hi，这里确实有访问越界的情况，在fillDist较大的时候需要对下标判断一下。

有时不会报错可能只是没有覆盖到一些关键的数据，但是此时已经污染内存了。

**Comment by amanohanei** [comment]
> 
> 
> Hi，这里确实有访问越界的情况，在fillDist较大的时候需要对下标判断一下。
> 
> 有时不会报错可能只是没有覆盖到一些关键的数据，但是此时已经污染内存了。

十分感谢，另外问下项目有控制难度的方案吗？basicEval.txt里的评估分值有点超纲了。。不太能理解。

**Comment by dhbloo** [comment]
代码里面没有做显式的难度控制，如果要调整难度的话，可以通过节点数或思考时间进行调整。

一个经验是节点数每次翻倍，大概+60elo，可以用来参考。

basicEval.txt里面写的有一些简略，其实就是配置的单线棋型[16种]与双线组合棋型[C(16,2)种]的估值和选点分值。棋型的顺序定义在[此处](https://github.com/dhbloo/Rapfi-gomocup/blob/e2379d9fb956a198bd5aee24a3765f8544130ba3/AIRapFi/Evaluator.h#L27)。这个分值表来源是手动调整的估值，目前还算一个比较好的水平，但说不上就一定调到了最优数值（因为调参本就是件比较困难的事）。通过调整参数，可以显著地影响引擎下棋的风格与棋力。

**Comment by amanohanei** [comment]
感觉棋力和 https://gomocalc.com/#/ 相比有些差距，是因为您那边有数值调优吗？

**Comment by dhbloo** [comment]
Gomocalc上使用的是最新的Rapfi版本，在这一版的基础上重写了整个程序，棋力也更强。新版目前暂时没有开源计划。

**Comment by amanohanei** [comment]
好的，十分感谢
